<?php

/**
 * Implementation of hook_menu().
 */
function cenus_contact_menu() {
   $items = array();
  $items['cenus_contact/send'] = array(
    'page callback' => 'cenus_contact_send',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function cenus_contact_send() {
    $email_to = variable_get('site_mail', ini_get('sendmail_from')); // change with your email
    $name     = $_POST['name'];
    $email    = $_POST['email'];
    $subject   = $_POST['subject'];
    $message    = $_POST['message'];

    $headers  = "From: $email\r\n";
    $headers .= "Reply-To: $email\r\n";

    if(mail($email_to, $subject, $message, $headers)){
        echo "success";
    }
    else{
        echo "failed";
    }

}

